# Generated by Django 4.2.3 on 2023-07-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0002_alter_video_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="thumbnail_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="video_url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="thumbnail_file",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.CharField(max_length=100),
        ),
    ]
