# Generated by Django 4.2.3 on 2023-07-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0003_video_thumbnail_url_video_video_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="date_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="duration",
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="signed_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="thumbnail_signed_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
