# Generated by Django 4.2.3 on 2023-07-27 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0004_video_date_time_video_duration_video_signed_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="signed_url",
        ),
        migrations.RemoveField(
            model_name="video",
            name="thumbnail_signed_url",
        ),
        migrations.RemoveField(
            model_name="video",
            name="thumbnail_url",
        ),
        migrations.RemoveField(
            model_name="video",
            name="video_url",
        ),
    ]
