# Generated by Django 4.2.3 on 2023-07-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0005_remove_video_signed_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="duration",
            field=models.IntegerField(null=True),
        ),
    ]
