# Generated by Django 4.2.6 on 2023-10-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0007_video_unique_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="embeddings",
            field=models.TextField(blank=True),
        ),
    ]
